### ISSUE TITLE
Support for AJAX follow / unfollow.

### ISSUE THREAD

**Issue by nkeilar** [caffeinehit/django-follow#19]
Seems the default views don't handle this, and there is no js included.

**Comment by nkeilar** [comment]
Okay, seems the js request must be a POST. i'd probably not enforce that ajax request be made via POST by moving that check below the ajax one. Just my 2c.

**Comment by flashingpumpkin** [comment]
I made it require POST requests in a conscious decision to not allow any data alteration to happen within GET requests - which includes cross site requests (including iFrames to the follow URL, submitting GET (JSONP) from other domains). Not going to change that. ;)
