### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by lilac** [caffeinehit/django-follow#2]
When register follow with an model in which object fields may contain non-assic strings, system would complain assic decode error.

Change the **unicode** method in Follow with the following solves the problem.

def **unicode**(self):
    return self.get_object().**unicode**()

**Comment by flashingpumpkin** [comment]
Hi,

Could you post a complete traceback of what is happening? 

Thanks

**Comment by flashingpumpkin** [comment]
I believe this is fixed. There was a lot of refactoring that happened and most of the code changed.
