### ISSUE TITLE
Incorrect documentation (FollowManager classmethods)

### ISSUE THREAD

**Issue by kylef** [caffeinehit/django-follow#3]
> - `FollowManager.get_follows(model_or_object)`:
>   Returns all the Follow objects associated with a certain model or object.

FollowManager does not have get_follows as a class method. It would be `FollowManager().get_follows(model_or_object) or even Follow.objects.get_follows(model_or_object).

Its not only this, but quite a lot of the README is incorrect. I think it should also be noted that "follow_url" must be used via POST and not GET.

**Comment by flashingpumpkin** [comment]
Fair point. I shall change the docs as soon as I've got a minute on my hands. (Pull requests are very welcome too ;))
