### ISSUE TITLE
TemplateSyntaxError

### ISSUE THREAD

**Issue by rlander** [caffeinehit/django-follow#4]
Hello there!

After installing django-follow and syncdb'ing I'm getting the following error:

http://pastie.org/2788611

After a few minutes of debugging I'm not sure what's going on. 

It seems that follow.utils.register() correctly adds the foreignkey to the model, but the new field is not created inside the DB.

In the python shell a new instance of models.Follow has a property called "post_id". However, the db table is not created (I verified this inside the db).

My env:
- Django 1.3.1
- South 0.7.3

Thanks for the help!

**Comment by flashingpumpkin** [comment]
- Did you try running the tests?
- Did you register the model before or after the first syncdb? 

If you registered it _after_ the first time you synced, django-follow created the table without any additional fields. In that case you'd have to write a migration - or drop the table and resync. I'll have to add this to the README

**Comment by rlander** [comment]
After completely wiping the DB it works correctly.

**Comment by rlander** [comment]
Sorry, I accidentally closed the issue before seeing your reply.

I figured out the problem because all the tests were passing but manual navigation was throwing an exception.

Thanks for the help and for sharing this the code!

**Comment by flashingpumpkin** [comment]
Cool
