### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by aglyzov** [caffeinehit/django-follow#9]
I believe there is a bug in the Follow.**unicode** method:
        return '%s' % self.target
should really be:
        return u'%s' % self.target

Otherwise you've got <Follow: [Bad Unicode data]> if a representation of target has non-ascii characters.

For instance in my project this even leads to a 500 page with exception thrown by the logger function,
the code is:
    label = unicode(follow_inst)
Note, I tried str(...) and repr(...) with the same result (because Model.**str** still uses force_unicode)

When I applied the fix mentioned above, the error gone.

**Comment by flashingpumpkin** [comment]
Indeed

On 6 February 2012 20:51, aglyzov
reply@reply.github.com
wrote:

> I believe there is a bug in the Follow.**unicode** method:
>        return '%s' % self.target
> should really be:
>        return u'%s' % self.target
> 
> Otherwise you've got <Follow: [Bad Unicode data]> if a representation of target has non-ascii characters.
> 
> For instance in my project this even leads to a 500 page with exception thrown by the logger function,
> the code is:
>    label = unicode(instance)
> Note, I tried str(...) and repr(...) with the same result (because Model.**str** still uses force_unicode)
> 
> When I applied the fix mentioned above, the error gone.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/caffeinehit/django-follow/issues/9

## 

http://twitter.com/flashingpumpkin
http://github.com/flashingpumpkin
